version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: 054037133502.dkr.ecr.ap-southeast-5.amazonaws.com/mais-splkadmin:latest
        container_name: mais_admin
        volumes:
            - ./resources/views:/var/www/html/resources/views # For Dev
            - ./app:/var/www/html/app # For Dev
            - ./database:/var/www/html/database # For Dev
            - ./routes:/var/www/html/routes # For Dev
            - ./composer.json:/var/www/html/composer.json:rw
            - ./composer.lock:/var/www/html/composer.lock:rw
        ports:
            - "8050:80"

        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
        restart: always
