version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: mais_dashboard_app
        volumes:
            - /home/static_files:/var/www/static_files
            - build-assets:/var/www/html/public/build
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1

    webserver:
        image: nginx:alpine
        container_name: mais_dashboard_server
        volumes:
            - ./public/assets:/var/www/html/public/assets
            - /home/static_files:/var/www/static_files
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - build-assets:/var/www/html/public/build

        ports:
            - "7080:80"

        depends_on:
            - app

volumes:
    build-assets:
