version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: mais_dashboard_be
        volumes:
            - .:/var/www/html
            - /home/static_files:/var/www/static_files # Add this line

        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1

        command: >
            sh -c "mkdir -p /var/www/static_files/fin_statement_attachments &&
                   chown -R www-data:www-data /var/www/static_files &&
                   chmod -R 775 /var/www/static_files &&
                   chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
                   chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
                   php-fpm"

    webserver:
        image: nginx:alpine
        container_name: mais_dashboard_server
        volumes:
            - .:/var/www/html
            - /home/static_files:/var/www/static_files
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "7080:80"

        depends_on:
            - app
