version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: mais_dashboard_be
    volumes:
      - .:/var/www/html
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1

    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
             chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
             php-fpm"

  webserver:
    image: nginx:alpine
    container_name: mais_dashboard_server
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "7080:80"

    depends_on:
      - app

